# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splashUpstream.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_US_splash(object):
    def setupUi(self, US_splash):
        US_splash.setObjectName("US_splash")
        US_splash.resize(578, 338)
        self.centralwidget = QtWidgets.QWidget(US_splash)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"    color:#43dde6;\n"
"    background-color:rgb(20, 21, 38);\n"
"    border-radius:10px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 140, 561, 81))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLineWidth(1)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(170, 0, 231, 161))
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/images/UPSTREAM LOGO CIRCLE transparent.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(73, 230, 411, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    text-align:center;\n"
"    border-style:none;\n"
"    background-color:rgb(56, 83, 112);\n"
"    border-radius:10px;\n"
"    color:rgb(20, 21, 38);\n"
"}\n"
"\n"
"QProgressBar::chunk{\n"
"    border-radius:10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.0568182, y1:0.472, x2:0.994, y2:0.449, stop:0 rgba(67, 221, 230, 255), stop:1 rgba(240, 240, 240, 255));\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(0, 260, 561, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_2.raise_()
        self.progressBar.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.verticalLayout.addWidget(self.frame)
        US_splash.setCentralWidget(self.centralwidget)

        self.retranslateUi(US_splash)
        QtCore.QMetaObject.connectSlotsByName(US_splash)

    def retranslateUi(self, US_splash):
        _translate = QtCore.QCoreApplication.translate
        US_splash.setWindowTitle(_translate("US_splash", "MainWindow"))
        self.label.setText(_translate("US_splash", "<html><head/><body><p><span style=\" font-size:36pt;\">UPSTREAM</span></p></body></html>"))
        self.label_3.setText(_translate("US_splash", "loading..."))
import imgs_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    US_splash = QtWidgets.QMainWindow()
    ui = Ui_US_splash()
    ui.setupUi(US_splash)
    US_splash.show()
    sys.exit(app.exec_())
